os: Visual Studio 2015

platform:
  - x64

configuration:
  - Debug
  - Release

matrix:
  fast_finish: true

build_script:
  - $vsixPath = "$($env:USERPROFILE)\sqlite-wp81-winrt-3081002.vsix"
    (New-Object Net.WebClient).DownloadFile('https://visualstudiogallery.msdn.microsoft.com/5d97faf6-39e3-4048-a0bc-adde2af75d1b/file/132406/15/sqlite-wp81-winrt-3081002.vsix', $vsixPath)
    "`"C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\VSIXInstaller.exe`" /q /a $vsixPath" | out-file ".\install-vsix.cmd" -Encoding ASCII
    & .\install-vsix.cmd
  - SET
  - cd C:\Program Files
  - DIR
  - cd C:\Program Files (x86)
  - DIR
  - CD
  - cd ..
  - CD
  - git clone https://github.com/HowardHinnant/date
  - git clone https://github.com/rbock/sqlpp11
  - cd sqlpp11-connector-sqlite3
  - CD
  - echo %configuration%
  - mkdir build
  - cd build
  - cmake --version
  - cmake .. -DCMAKE_CXX_FLAGS="/EHsc /wd4503" -DCMAKE_GENERATOR_PLATFORM=x64
  - cmake --build . --config %configuration%
  - ctest . --build-config %configuration%

