os: Visual Studio 2015

platform:
  - x64

configuration:
  - Debug
  - Release

matrix:
  fast_finish: true

build_script:
  - SET
  - choco install wget
  - $vsixPath = "$($env:USERPROFILE)\sqlite-winrt81-3110100.vsix"
  - (New-Object Net.WebClient).DownloadFile('https://visualstudiogallery.msdn.microsoft.com/1d04f82f-2fe9-4727-a2f9-a2db127ddc9a/file/111148/32/sqlite-winrt81-3110100.vsix', $vsixPath)
  #- "`"C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\VSIXInstaller.exe`" /q /a $vsixPath" | out-file ".\install-vsix.cmd" -Encoding ASCII
  #- & .\install-vsix.cmd
  - CD
  - cd ..
  - CD
  - git clone https://github.com/HowardHinnant/date
  - git clone https://github.com/rbock/sqlpp11
  - cd sqlpp11-connector-sqlite3
  - CD
  - echo %configuration%
  - mkdir build
  - cd build
  - cmake --version
  - cmake .. -DCMAKE_CXX_FLAGS="/EHsc /wd4503" -DCMAKE_GENERATOR_PLATFORM=x64
  - cmake --build . --config %configuration%
  - ctest . --build-config %configuration%

