os: Visual Studio 2015

platform:
  - x64

services:
  - sqlite3

configuration:
  - Debug
  - Release

matrix:
  fast_finish: true

build_script:
  - SET
  - cd C:\Program Files
  - DIR /s
  - CD
  - cd ..
  - CD
  - git clone https://github.com/HowardHinnant/date
  - git clone https://github.com/rbock/sqlpp11
  - cd sqlpp11-connector-sqlite3
  - CD
  - echo %configuration%
  - mkdir build
  - cd build
  - cmake --version
  - cmake .. -DCMAKE_CXX_FLAGS="/EHsc /wd4503" -DCMAKE_GENERATOR_PLATFORM=x64
  - cmake --build . --config %configuration%
  - ctest . --build-config %configuration%

