language: cpp

os:
  - linux
  - osx

sudo: required
dist: trusty
addons:
  apt:
    packages:
    - sqlite3
    - libboost-dev

compiler:
  - clang
  - gcc

env:
  - CONFIG=Release
  #- CONFIG=Debug

notifications:
 email:
   on_success: change
   on_failure: always

install:
  - g++ --version
  - cmake --version
  - pwd
  - PROJECT_DIR="$PWD"
  - BRANCH=`git rev-parse --abbrev-ref HEAD`
  - cd ..
  - pwd
  - git clone https://github.com/HowardHinnant/date
  - cd date
  - git checkout tags/v1.0.0
  - cd ..
  - git clone https://github.com/rbock/sqlpp11
  - if [ "$BRANCH" != "master" ]; then
      cd sqlpp11
      && git checkout develop
      && cd ..
      ;
    fi
  - cd "$PROJECT_DIR"

before_script:
   - mkdir build
   - cd build
   - if [[ "$CXX" = "g++" && "$CONFIG" = "Debug" && "$TRAVIS_OS_NAME" = "linux" ]]; then export CXXFLAGS="--coverage"; fi
   - cmake .. -DCMAKE_BUILD_TYPE=$CONFIG

script:
   - make VERBOSE=1
   - cmake --build . --config $CONFIG
   - ctest --output-on-failure

after_script:
  - ../coveralls
